spring:
  kafka:
    bootstrap-servers: localhost:9092
    template: # vidi sta rade ovi
      default-topic: notificationTopic
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.microservice.notification_service.event.OrderPlacedEvent
  zipkin:
    base-url: http://localhost:{port}
  eureka:
    client:
      service-url:
        defaultZone: http://eureka:password@localhost:8761/eureka
  application:
    name: notification-service

server:
  port: 0
management:
  endpoint:
    web:
      exposure:
        include: prometheus