spring:
  kafka:
    bootstrap-servers: localhost:9092
    template: # vidi sta rade ovi
      default-topic: notificationTopic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.microservice.orderservice.event.OrderPlacedEvent
  zipkin:
    base-url: http://localhost:{port}
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order-service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: always
#Ressilence 4j properties
resilience4j:
  retry: #retry properties
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 5s
  timelimiter: #timeout properties
    instances:
      inventory:
        timeout-duration: 3s
  circuitbreaker:
    instances:
      inventory:
        register-health-indicator: true #we want to see different states of circuit breaker
        event-consumer-buffer-size: 10 # how much buffer size it will take for the event
        sliding-window-type: COUNT_BASED # wont open the circuti breakerright away
        sliding-window-size: 5 # after 5 failed reqest will change to open state
        failure-rate-threshold: 50 #50 percent?
        wait-duration-in-open-state: 5s #how much to wate before going to the half open state
        permitted-number-of-calls-in-half-open-state: 3 #how many cals we have to alow before we check the counication for?
        automatic-transition-from-open-to-half-open-enabled: true #automaticly transiion between open and half open
#Kafka properties

